language: node_js
node_js:
  - "4"
env:
  global:
    - BIN="node" EXPORTS="commonjs" NPM_VERSION="^2.0.0"
    - OPTION="" QUERY="" TEST_BUILDS=false TRANSPILER="none"
    - LOADER="requirejs" RUNNER_PATH="node_modules/lodash/test"
    - SAUCE_PATH="$RUNNER_PATH/saucelabs.js" SAUCE_USERNAME="lodash"
    - secure: "HUCzn6i9XZ53278fYMICHuHWaVtTZmJCfY4wv3BEu57CGshw9T399Vxul849vIusw3x9cf4iNrrry0RaZga7KfaJIVSESy4zeY4vnsJ+5QCiXGbobpNPYnhU50eTo95MqDh1/Uds+cv2HCo+4VH8yb+6k/p9xX0CC3TvvToX60M="
  matrix:
    -
#    - BIN="rhino" OPTION="-opt -1 -require"
#    - BIN="ringo" OPTION="-o -1"
    - EXPORTS="es"  TRANSPILER="babel"
    - EXPORTS="node"
    - EXPORTS="npm"
    - TEST_BUILDS=true
matrix:
  include:
    - node_js: "0.8"
      env: NPM_VERSION="~1.4.0"
    - node_js: "0.8"
      env: EXPORTS="npm" NPM_VERSION="~1.4.0"
    - node_js: "0.10"
      env:
    - node_js: "0.10"
      env: EXPORTS="npm"
    - node_js: "0.12"
      env:
    - node_js: "0.12"
      env: EXPORTS="npm"
    - node_js: "4"
      env: EXPORTS="amd"
    - node_js: "4"
      env: EXPORTS="amd" LOADER="curl"
    - node_js: "4"
      env: EXPORTS="amd" LOADER="dojo"
    - node_js: "4"
      env: EXPORTS="amd"
    - node_js: "4"
      env: EXPORTS="amd" LOADER="curl"
    - node_js: "4"
      env: EXPORTS="amd" LOADER="dojo"
git:
  depth: 10
branches:
  only:
    - master
before_install:
  - "nvm use $TRAVIS_NODE_VERSION"
  - "npm config set loglevel error"
  - "npm i -g npm@\"$NPM_VERSION\""
  - "git clone --depth=10 --branch=master git://github.com/lodash/lodash ./node_modules/lodash && cd $_ && npm i && cd ../../"
#  - "[ $BIN != 'rhino' ] || (sudo mkdir /opt/rhino-1.7.6 && sudo wget --no-check-certificate -O $_/js.jar https://lodash.com/_travis/rhino-1.7.6.jar)"
#  - "[ $BIN != 'rhino' ] || (echo -e '#!/bin/sh\\njava -jar /opt/rhino-1.7.6/js.jar $@' | sudo tee /usr/local/bin/rhino && sudo chmod +x /usr/local/bin/rhino)"
#  - "[ $BIN != 'ringo' ] || (wget --no-check-certificate https://lodash.com/_travis/ringojs-0.11.zip && sudo unzip ringojs-0.11 -d /opt && rm ringojs-0.11.zip)"
#  - "[ $BIN != 'ringo' ] || (sudo ln -s /opt/ringojs-0.11/bin/ringo /usr/local/bin/ringo && sudo chmod +x $_)"
  - "OUTPUT_PATH=\"./$EXPORTS\" && TARGET_PATH=\"../../../$EXPORTS/index.js\""
  - "[ $EXPORTS != 'amd' ] || TARGET_PATH=\"../../../amd/main.js\""
  - "[ $EXPORTS != 'amd' ] || (QUERY=\"build=$TARGET_PATH&loader=$LOADER&noglobals=true\" && TAGS=\"$LOADER,amd,development\")"
  - "[ $EXPORTS != 'amd' ] || npm i chalk@\"^1.0.0\" ecstatic@\"0.8.0\" request@\"^2.0.0\" sauce-tunnel@\"2.2.3\""
  - "[ $EXPORTS != 'es' ]  || TARGET_PATH=\"../../../$EXPORTS/lodash.js\""
  - "[ $EXPORTS != 'npm' ] || OUTPUT_PATH=\"./npm/node_modules\""
  - "[ $TEST_BUILDS == true ]   || (npm i && node ./bin/lodash modularize exports=$EXPORTS -o $OUTPUT_PATH)"
  - "[ $TRANSPILER != 'babel' ] || npm i -g babel@\"^5.0.0\""
  - "[ $TRANSPILER != 'babel' ] || babel ./$EXPORTS --out-dir ./$EXPORTS"
  - "[ $EXPORTS != 'npm' ] || (cd ./npm && cp ../test/npm/index.js ./index.js && cd ../)"
script:
  - "[ $EXPORTS != 'amd' ] || node $SAUCE_PATH name=\"lodash tests\"     runner=\"$RUNNER_PATH/index.html?$QUERY\"      tags=\"$TAGS\""
  - "[ $EXPORTS != 'amd' ] || node $SAUCE_PATH name=\"backbone tests\"   runner=\"$RUNNER_PATH/backbone.html?$QUERY\"   tags=\"$TAGS,backbone\""
  - "[ $EXPORTS != 'amd' ] || node $SAUCE_PATH name=\"underscore tests\" runner=\"$RUNNER_PATH/underscore.html?$QUERY\" tags=\"$TAGS,underscore\""
#  - "[ $EXPORTS != 'amd' ] || node $SAUCE_PATH name=\"lodash tests\" runner=\"$RUNNER_PATH/index.html?$QUERY\" tags=\"$TAGS,ie-compat\" compatMode=7"
  - "[ $EXPORTS == 'amd' ] || [ $TEST_BUILDS == true ]  || $BIN $OPTION $RUNNER_PATH/test.js $TARGET_PATH"
  - "[ $EXPORTS == 'amd' ] || [ $TEST_BUILDS == false ] || node ./test/test.js --time-limit 45m"
