language: node_js
node_js:
  - "0.6"
  - "0.10"
git:
  depth: 1
branches:
  only:
    - master
before_install:
  - "git clone --depth=1 --branch=master git://github.com/lodash/lodash.git ./node_modules/lodash"
script:
  - "node ./test/test.js --time-limit 48m"
